name: Build and push to ACR

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: quick Composer sanity check outside Docker for clearer errors
      - name: PHP 8.1 + Composer check (optional)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
      - name: Composer validate (no scripts) (optional)
        run: |
          composer --version
          composer validate --no-interaction || true
          composer install --no-dev --prefer-dist --no-scripts --no-progress -vvv || true

      # Sanity check DNS for ACR (helps catch a bad login server secret)
      - name: DNS check
        run: |
          echo "ACR: $ACR_LOGIN_SERVER"
          nslookup "$ACR_LOGIN_SERVER" || true
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push (no cache to pick up Dockerfile changes)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/laravel-aca:latest
          build-args: |
            GITHUB_TOKEN=${{ secrets.GH_PAT || '' }}
