name: Build and push to ACR
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain   # show full logs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show branch and files (debug)
        run: |
          git rev-parse --abbrev-ref HEAD
          ls -la
          sed -n '1,120p' Dockerfile || true

      # Composer dry-run OUTSIDE Docker for clearer errors
      - name: PHP 8.1 + Composer (diag)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
      - name: Composer diagnose & install (no-scripts) outside Docker
        run: |
          composer --version
          composer diagnose || true
          composer install --no-dev --prefer-dist --no-scripts --no-progress -vvv || true

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push (no cache, full logs)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/laravel-aca:latest
          build-args: |
            GITHUB_TOKEN=${{ secrets.GH_PAT || '' }}
